Renamed enum dependency to enum34 due conflicts with Python 3.6.1
enumeration type:
Why Python 3.6.1 throws AttributeError: module 'enum' has no attribute 'IntFlag'?
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag/